name: qlutter_backend
description: Qlutter API
version: 0.1.1
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  conduit: ^4.3.6
  conduit_core: ^4.3.6
  conduit_postgresql: ^4.3.6 
  jaguar_jwt: 3.0.0
  intl: ^0.18.0
  json_annotation: ^4.8.0

dev_dependencies:
  test: ^1.16.5
  conduit_test: ^4.3.6
  build_runner: ^2.3.3
  json_serializable: ^6.6.1